apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: "{{ .Values.functions.patchAndTransform.package }}:{{ .Values.functions.patchAndTransform.version }}"
  packagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
