apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: "{{ .Values.providers.awsS3.package }}:{{ .Values.providers.awsS3.version }}"
  packagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
