apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
spec:
  package: "{{ .Values.providers.awsEks.package }}:{{ .Values.providers.awsEks.version }}"
  packagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
