{{- if .Values.vaultSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tailscale-operator-oauth
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: tailscale/operator
  destination:
    name: operator-oauth
    create: true
    labels:
      app.kubernetes.io/name: tailscale-operator
    transformation:
      excludeRaw: true
      templates:
        client_id:
          text: '{{ `{{ index .Secrets "client_id" }}` }}'
        client_secret:
          text: '{{ `{{ index .Secrets "client_secret" }}` }}'
  refreshAfter: 1h
  vaultAuthRef: secrets/transit-vault-auth
{{- end }}
