{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tailscale-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.externalSecret.ssmClientIdKey }}
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.externalSecret.ssmClientSecretKey }}
{{- end }}
