apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: http-echo
          image: hashicorp/http-echo:latest
          args:
            - -text=hello from eks
          ports:
            - containerPort: {{ .Values.ports.httpEcho }}
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.httpEcho }}
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.httpEcho }}
            initialDelaySeconds: 3
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
