{
 "title": "OOMKilled and Restarts",
 "description": "Contains panels that show:\r\n1. restarts per pod\r\n2. oom killed processes in the node\r\n3. pods that got oom killed",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=~\"_kube-state-metrics|kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=~\"kube-state-metrics|_kube-state-metrics\", cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(sum by (container,pod)(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[5m]))>0)",
     "legendFormat": "Restart 5 Minutes: {{pod}}"
    },
    {
     "expr": "sum by (pod,container,namespace)(kube_pod_container_status_restarts_total{namespace=\"$namespace\"})>0",
     "legendFormat": "Restart Total: {{pod}}"
    }
   ]
  },
  {
   "title": "Pods with OOMkilled ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",namespace=~\"$namespace\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM killed processes per node delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "delta(node_vmstat_oom_kill[5m])>0",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}