{{- if .Values.vaultSecrets.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tailscale-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: tailscale/operator
  destination:
    name: tailscale-auth
    create: true
    labels:
      app.kubernetes.io/name: tailscale
    transformation:
      excludeRaw: true
      templates:
        auth-key:
          text: '{{ `{{ index .Secrets "auth-key" }}` }}'
  refreshAfter: 1h
  vaultAuthRef: secrets/transit-vault-auth
{{- end }}
