apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: tailscale-auth
    creationPolicy: Owner
  data:
    - secretKey: auth-key
      remoteRef:
        key: {{ .Values.externalSecret.ssmKey }}
