providers:
  awsS3:
    package: "xpkg.upbound.io/upbound/provider-aws-s3"
    version: "v2.3.0"
  awsEks:
    package: "xpkg.upbound.io/upbound/provider-aws-eks"
    version: "v2.3.0"
  awsEc2:
    package: "xpkg.upbound.io/upbound/provider-aws-ec2"
    version: "v2.3.0"
  awsIam:
    package: "xpkg.upbound.io/upbound/provider-aws-iam"
    version: "v2.3.0"
  kubernetes:
    package: "xpkg.crossplane.io/crossplane-contrib/provider-kubernetes"
    version: "v1.2.0"

functions:
  patchAndTransform:
    package: "xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform"
    version: "v0.10.0"
  autoReady:
    package: "xpkg.crossplane.io/crossplane-contrib/function-auto-ready"
    version: "v0.6.0"
