apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudflared
data:
  config.yaml: |
    ingress:
    {{- if .Values.directIngress.enabled }}
      {{- range .Values.directIngress.rules }}
      - hostname: {{ .hostname | quote }}
        service: {{ .service }}
      {{- end }}
    {{- else }}
      - hostname: "*.{{ .Values.cloudflare.domain }}"
        service: https://cilium-gateway-{{ .Values.gateway.name }}.{{ .Values.gateway.namespace }}.svc.cluster.local:{{ .Values.ports.gateway.https }}
        originRequest:
          noTLSVerify: true
    {{- end }}
      - service: http_status:404
