{{- if .Values.vaultSecrets.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: cloudflare/tunnel-token
  destination:
    name: cloudflared-tunnel-credentials
    create: true
    labels:
      app.kubernetes.io/name: cloudflared
    transformation:
      excludeRaw: true
      templates:
        tunnel-token:
          text: '{{ `{{ index .Secrets "tunnel-token" }}` }}'
  refreshAfter: 1h
  vaultAuthRef: secrets/transit-vault-auth
{{- end }}
