{
 "title": "Tetragon \"kubectl exec\" Audit",
 "description": "Dashboard showing \"kubectl exec\" runs for selected clusters and namespaces, split by Kubernetes workload.",
 "tags": [
  "Tetragon",
  "security"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "export_job",
    "label": "export job",
    "query": {}
   },
   {
    "name": "cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "container_runtime", "label": "container runtime", "query": "/usr/sbin/runc" }
  ]
 },
 "panels": [
  {
   "title": "Malicious \"kubectl exec\" Events by Workload",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~\"$cluster\", job=\"$export_job\"} |~ \"process_exec\" |~ \"$namespace\" |~ \"$container_runtime\" | json | process_exec_process_pod_namespace =~ \"$namespace\" and process_exec_parent_binary=`$container_runtime` and process_exec_parent_pid != 1 [$__range])) by (process_exec_process_pod_workload)",
     "legendFormat": "{{process_exec_process_pod_workload}}"
    }
   ]
  },
  {
   "title": "Runtime Events by Workload",
   "type": "gauge",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the Kubernetes workloads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~\"$cluster\", job=\"$export_job\"} |~\"process_exec\" |~\"$namespace\" | json | (process_exec_process_pod_namespace=~\"$namespace\" and (process_exec_parent_binary=`/bin/sh` or process_exec_parent_binary=`/usr/bin/sh` or process_exec_parent_binary=`/bin/bash` or process_exec_parent_binary=`/usr/bin/bash`) or (process_exec_parent_binary=`$container_runtime` and process_exec_parent_pid != 1)) [$__range])) by (process_exec_process_pod_workload)",
     "legendFormat": "{{process_exec_pod_workload}}"
    }
   ]
  },
  {
   "title": "Malicious \"kubectl exec\" Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", job=\"$export_job\"} |~\"process_exec\" |~\"$namespace\" |~\"$container_runtime\" | json | process_exec_process_pod_namespace=~\"$namespace\" and process_exec_parent_binary=`$container_runtime` and process_exec_parent_pid != 1"
    }
   ]
  }
 ]
}